<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Product;

         class ProductSeeder extends Seeder
         {
            /**
             * Run the database seeds.
            */
         public function run(): void
         {
            DB::table('products')->insert([
            [
               'name' => 'Plum 15% Vitamin C Serum for Glowing Skin | For Oily, Dry & Combination Skin',
               'price' => 593,
                'category' => 'Skin Care',
                'discount' => 650,
               'gallery' => 'product_img/p06.webp',
                'description' => 'Plum 15% Vitamin C Serum for Glowing Skin | For Oily, Dry & Combination Skin',
               'created_at' => now(),
               'updated_at' => now(),
              
            ],
               [
               'name' => 'NIVEA MEN Pure Impact Shower Gel, 250ml (Hair, Face & Body Wash)',
               'price' => 298,
               'category' => 'Skin Care',
                 'discount' => 350,
               'gallery' => 'product_img/p07.webp',
                'description' => 'NIVEA MEN Pure Impact Shower Gel, 250ml (Hair, Face & Body Wash)',
               'created_at' => now(),
               'updated_at' => now(),
              
            ],
               [
               'name' => 'La Shield Fisico SPF 50 PA+++ Mineral Sunscreen | Water Resistant Upto 8 hours',
               'price' => 500,
               'category' => 'Skin Care',
               'discount' => 100,
                'gallery' => 'product_img/p08.webp',
               'description' => 'La Shield Fisico SPF 50 PA+++ Mineral Sunscreen | Water Resistant Upto 8 hours',
               'created_at' => now(),
               'updated_at' => now(),
            
            ],
               [
               'name' => 'L Oreal Paris Glycolic Bright Daily Foaming Face Cleanser, 100ml',
               'price' => 290,
                'category' => 'Skin Care',
               'discount' => 450,
               'gallery' => 'product_img/p09.webp',
                'description' => 'L Oreal Paris Glycolic Bright Daily Foaming Face Cleanser, 100ml',
               'created_at' => now(),
               'updated_at' => now(),
               
            ],
               [
               'name' => 'Swiss Beauty Hydra Anti Wrinkle Eye Serum Patch',
               'price' => 480,
               'category' => 'Skin Care',
                  'discount' => 600,
               'gallery' => 'product_img/p010.webp',
               'description' => 'Swiss Beauty Hydra Anti Wrinkle Eye Serum Patch',
                  'created_at' => now(),
               'updated_at' => now(),
            ],
               [
               'name' => 'Maybelline New York Matte Lipstick, Intense Colour, Keeps Lips Moisturised',
               'price' => 570,
               'category' => 'Skin Care',
                  'discount' => 900,
               'gallery' => 'product_img/p011.webp',
               'description' => 'Maybelline New York Matte Lipstick, Intense Colour, Keeps Lips Moisturised',
                  'created_at' => now(),
               'updated_at' => now(),
            ],
               [
               'name' => 'PONDs Bright Beauty Anti-Dullness & Brightening Facewash With Niacinamide',
               'price' => 250,
               'category' => 'Skin Care',
                  'discount' => 370,
               'gallery' => 'product_img/p012.webp',
               'description' => 'PONDs Bright Beauty Anti-Dullness & Brightening Facewash With Niacinamide',
                  'created_at' => now(),
               'updated_at' => now(),
            ],
               [
               'name' => 'Elle 18 Eye Drama Kajal, Matte Finish, Super Black, Smudgeproof & Waterproof, 0.35 G',
               'price' => 490,
               'category' => 'Skin Care',
                  'discount' => 700,
               'gallery' => 'product_img/p013.webp',
               'description' => 'Elle 18 Eye Drama Kajal, Matte Finish, Super Black, Smudgeproof & Waterproof, 0.35 G',
                  'created_at' => now(),
               'updated_at' => now(),
            ],
            [
            'name' => 'Busy Bubb - Wooden Tetris Puzzle Game for Kids | Russian Blocks Puzzle | Wood Intelligence Puzzle for Kids',
            'price' => 199,
            'category' => 'Toys',
            'discount' => 300,
            'gallery' => 'product_img/p02.webp',
            'description' => 'Exciting Hot Wheels 5 car pack for kids and collectors.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Mirana C-Type USB Rechargeable Battery Powered Hover Football Indoor Floating Hoverball Soccer | Air Football Smart ',
            'price' => 698,
            'category' => 'Toys',
            'discount' => 750,
            'gallery' => 'product_img/p03.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Fun Express 4x4 Mini Monster Friction Power Truck Pack of 1 Kids Age 3-8 | 360 Drift Stunt Car | Push & Go Forward 
         ',
            'price' => 69,
            'category' => 'Toys',
            'discount' => 100,
            'gallery' => 'product_img/p05.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'SMARTOYS | Wooden Toys | Fun & engageing | Eco-Friendly Colors & Materials  ',
            'price' => 298,
            'category' => 'Toys',
            'discount' => 320,
            'gallery' => 'product_img/p03.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Toy Imagine Gyro Magic Lattoo Toys with Music and Lights Spinning Top Toy for Kids Boy Colourful Spinner Fidget Sound Tops Best Birthday Gift for Baby khilona Age 3+ Years Old Pack of 1 ',
            'price' => 162,
            'category' => 'Toys',
            'discount' => 180,
            'gallery' => 'product_img/p015.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Storio Toys Spinning Gyro Magic Lattoo with Music and Lights | Spinning Top Toy for Kids Boy | Colourful Spinner Fidget Sound Tops Best Birthday Gift for Baby ',
            'price' => 169,
            'category' => 'Toys',
            'discount' => 200,
            'gallery' => 'product_img/p016.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Toy Imagine™ Lattoo Spinning Launcher Gyro Top with Flashing Led Light Beyblade (Color May Vary). ',
            'price' => 158,
            'category' => 'Toys',
            'discount' => 190,
            'gallery' => 'product_img/p017.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Ratna Magic Blow Pipe Set of 2 Floating Ball Creative Magic Blowing Ball Toy Party Game for Kids & Adults',
            'price' => 88,
            'category' => 'Toys',
            'discount' => 100,
            'gallery' => 'product_img/p018.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Storio 3 Slides 24 Patterns Mini Projector Torch Toy Slide Flashlight Projector Torch for Kids Sleeping Story Toys for Toddlers, Educational Learning Toys,Space,Animal &Foods ',
            'price' => 169,
            'category' => 'Toys',
            'discount' => 200,
            'gallery' => 'product_img/p019.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Hindware Smart Appliances | Marvia 60 cm Chimney | 1000 CMH | Pyramid | Push Button | Efficient Dual LED Lamps and Double Baffle Filter | 5 Yrs Warranty on Motor & 2 Yrs on Product (Black) ',
            'price' => 5899,
            'category' => 'Kitchen',
            'discount' => 13400,
            'gallery' => 'product_img/p020.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Daikin 1.5 Ton 3 Star Inverter Split AC (Copper, PM 2.5 Filter, Triple Display, Dew Clean Technology, Coanda Airflow, 2024 Model, MTKL50U, White)',
            'price' => 37490,
            'category' => 'Kitchen',
            'discount' => 58400,
            'gallery' => 'product_img/p021.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Samsung 7 kg, Fully-Automatic Top Load Washing Machine with Diamond Drum (WA70A4002GS/TL, Imperial Silver) ',
            'price' => 15490,
            'category' => 'Kitchen',
            'discount' => 18400,
            'gallery' => 'product_img/p022.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Whirlpool 184 L 2 Star Direct-Cool Single Door Refrigerator (205 WDE CLS 2S SAPPHIRE BLUE-Z, Blue,2023 Model) ',
            'price' => 12490,
            'category' => 'Kitchen',
            'discount' => 13400,
            'gallery' => 'product_img/p023.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Samsung 183 L, 4 Star, Digital Inverter, Direct-Cool Single Door Refrigerator (RR20C1824CR/HL, Red, Camellia Purple, Base Stand Drawer) ',
            'price' => 16390,
            'category' => 'Kitchen',
            'discount' => 20400,
            'gallery' => 'product_img/p024.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Godrej 180 L 2 Star Advanced Capillary Technology, With Jumbo Vegetable Tray Direct Cool Single Door Refrigerator(RD EDGE 205B WRF PP BL, Pep Blue) ',
            'price' => 24490,
            'category' => 'Kitchen',
            'discount' => 27400,
            'gallery' => 'product_img/p025.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'LG 7 Kg 5 Star Wind Jet Dry Semi-Automatic Top Loading Washing Machine (P7020NGAZ, Dark Gray, Rat Away Feature) ',
            'price' => 11490,
            'category' => 'Kitchen',
            'discount' => 13400,
            'gallery' => 'product_img/p026.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Panasonic 20L Solo Microwave Oven (NN-ST26JMFDG, Silver, 51 Auto Menus)',
            'price' => 6490,
            'category' => 'Kitchen',
            'discount' => 8400,
            'gallery' => 'product_img/p027.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Daikin 0.8 Ton 3 Star, Fixed Speed Split AC (Copper, PM 2.5 Filter, 2022 Model, FTL28U, White)',
            'price' => 26490,
            'category' => 'Kitchen',
            'discount' => 30400,
            'gallery' => 'product_img/p028.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
          [
            'name' => 'NEW LEAF Premium Cotton Elastic Fitted…',
            'price' => 379,
            'category' => 'home',
            'discount' => 1500,
            'gallery' => 'product_img/p029.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Home Sizzler 144 TC Microfibre Kid Giraff…',
            'price' => 369,
            'category' => 'home',
            'discount' => 356,
            'gallery' => 'product_img/p030.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Sehaz Artworks Wall Decor Items For Livin…',
            'price' => 269,
            'category' => 'home',
            'discount' => 334,
            'gallery' => 'product_img/p031.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Khooti Jute Cushion Cover, 20x20 Inch (N…atural, Set of 2)',
            'price' => 260,
            'category' => 'home',
            'discount' => 345,
            'gallery' => 'product_img/p032.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Ajanta Quartz Ajanta Abstract Quartz Anal…',
            'price' => 478,
            'category' => 'home',
            'discount' => 678,
            'gallery' => 'product_img/p033.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'AERYS Digital Alarm Clock with Automatic…',
            'price' => 300,
            'category' => 'home',
            'discount' => 440,
            'gallery' => 'product_img/p034.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Homefab India Pack of 2 Royal Silky Cream…',
            'price' => 500,
            'category' => 'home',
            'discount' => 789,
            'gallery' => 'product_img/p035.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'innovative edge Reversi…',
            'price' => 498,
            'category' => 'home',
            'discount' => 670,
            'gallery' => 'product_img/p036.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'SPHINX Ribbed Pipe Ceramic Vase, Flower…',
            'price' => 368,
            'category' => 'home',
            'discount' => 400,
            'gallery' => 'product_img/p037.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
           
         [
            'name' => 'Womens Cotton Solid Narrow Pant',
            'price' => 499,
            'category' => 'women',
            'discount' => 1500,
            'gallery' => 'product_img/p038.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Textured Trousers for Women | Women Loose Fit Trousers | Womens High-Waisted Pant | Women Trousers Pants | Korean Trousers for Women',
            'price' => 567,
            'category' => 'women',
            'discount' => 786,
            'gallery' => 'product_img/p039.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Leather Belts For Women And Girls 3 Pcs Combo Stylish Waist Belt For Dresses Jeans (16068Lb), Multicolour',
            'price' => 499,
            'category' => 'women',
            'discount' => 678,
            'gallery' => 'product_img/p040.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Summer Caps for Women, Sun Hats for Girls with Printed Ribbon, Girls Cap for Summer, Beach caps, Suitable for Gardening, Beach, Boating, Fishing Beige',
            'price' => 699,
            'category' => 'women',
            'discount' => 800,
            'gallery' => 'product_img/p041.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Womens Viscose Printed Culotte Shorts',
            'price' => 478,
            'category' => 'women',
            'discount' => 678,
            'gallery' => 'product_img/p042.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'SHEZONE',
            'price' => 890,
            'category' => 'women',
            'discount' => 1140,
            'gallery' => 'product_img/p043.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => '2 Pcs Combo Belts for Women and Girls Stylish Waist Belt for Dresses Jeans Saree',
            'price' => 500,
            'category' => 'women',
            'discount' => 789,
            'gallery' => 'product_img/p044.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Womens Embroidered Anarkali Kurta with Pant and Dupatta Set-Ethnic Wear Pink',
            'price' => 699,
            'category' => 'women',
            'discount' => 670,
            'gallery' => 'product_img/p045.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Womens Solid Square Neck Raglan Sleeves Side Pocketed Polyester Fit and Flare Knee-Length Dress',
            'price' => 1300,
            'category' => 'women',
            'discount' => 2000,
            'gallery' => 'product_img/p046.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Zulaxy Photo Frame Hooks for Wall Without Drilling, 10 Pack Self Adhesive Hooks for Wall Heavy Duty Strong Nail Free for Hanging Photo Frame (Hanging Hook, Transparent) Stainless Steel',
            'price' => 259,
            'category' => 'improvement',
            'discount' => 1500,
            'gallery' => 'product_img/p047.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Johnson Sigma 4x24 inches Rectangle Shower Drain Channel | SS304 Grade Vertical Water Drain Channel| Floor Drain for Bathroom with Cockroach Trap | 2 Year Warranty (T3391C2- Stainless Steel)',
            'price' => 3499,
            'category' => 'improvement',
            'discount' => 7286,
            'gallery' => 'product_img/p048.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'SPARTAN BS-02 8-in-1 Pc Screw Driver Kit With 3 Flat Blades, 3 Phillips Head, 1 Round Poker Bar, Extension Rod| Multi-purpose Tool Set Screwdriver Set (Multicolor)',
            'price' => 187,
            'category' => 'improvement',
            'discount' => 678,
            'gallery' => 'product_img/p049.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
               [
            'name' => 'AKSHAR ENTERPRISE Plastic Solar And Charging Led Lantern Light Battery Bulb, Portable Camping And Home Emergency Lights With 2 Power Sources High Light Travel Battery Lantern Torch Lamp',
            'price' => 199,
            'category' => 'improvement',
            'discount' => 800,
            'gallery' => 'product_img/p050.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
            'updated_at' => now(),
         ],
         [
            'name' => 'Milton Bathroom Brush Heavy Duty Bathroom Cleaning Brush with Wiper ? Long Handle Floor Scrubber with 180 Rotation for Tile, Toilet, Shower & Wall Cleaning in Kitchen & Home',
            'price' => 299,
            'category' => 'improvement',
            'discount' => 678,
            'gallery' => 'product_img/p051.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'eCraftIndia Resting Buddha on Knee Metal Showpiece (7.5 cm x 5.38 cm x 9.38 cm, Brown, AGB506)',
            'price' => 297,
            'category' => 'improvement',
            'discount' => 340,
            'gallery' => 'product_img/p052.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'BUILDSKILL Long Nose Plier 6", Versatile Hand Tools, Used as Electrical Tools, Portable Cutting Plier, Anti Rust Black Phosphate Finish, Efficient Hardware Tools, Durable Tools for Home (Pack of 1)',
            'price' => 209,
            'category' => 'improvement',
            'discount' => 789,
            'gallery' => 'product_img/p053.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'UFI - UF036-HF001-ABS Blaze Health Faucet with 1 Meter 304SS Flexible Shower Tube',
            'price' => 1300,
            'category' => 'improvement',
            'discount' => 1670,
            'gallery' => 'product_img/p054.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Pishacho Mechanical Docking Pull-Down Kitchen Tap Dual Spray Mode, 360° Swivel Brass Durability',
            'price' => 5300,
            'category' => 'improvement',
            'discount' => 7000,
            'gallery' => 'product_img/p055.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
           [
        'name' => 'Jam & Honey Easel Board I 5 in 1 Easel I with Alphabets & Numbers I Education Toy for 3+ Year Kids (Blue & Red)',
        'price' => 959,
        'category' => 'Fun toys',
        'discount' => 1500,
        'gallery' => 'product_img/p056.webp',
        'description' => '5 in 1 educational easel board with alphabets and numbers for kids.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Kiddale Smart Animal Sound, Intelligence Book for Kids| Electronic, Music, Educational, EBook| Audio Learning Activities with Animal Songs|Learn and Play Sound Book for Kids| Gift for 1,2,3,4 Year',
        'price' => 1499,
        'category' => 'Fun toys',
        'discount' => 1786,
        'gallery' => 'product_img/p057.webp',
        'description' => 'Interactive animal sound book with music and learning activities for kids.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Solimo 3-in-1 Penguin Modern Slide & Swing for Indoor & Outdoor Use | for Kids 2-5 Years Old | Safe & Fun | Ideal for Boys & Girls | Toy for Kids | Easy Assembly, Blue',
        'price' => 4187,
        'category' => 'Fun toys',
        'discount' => 6778,
        'gallery' => 'product_img/p058.webp',
        'description' => '3-in-1 penguin slide and swing set for indoor and outdoor play.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Jam & Honey 3-in-1 Puppy Push Ride-On, Rocker & Balance Board | for Kids 1-4 Years Old | Non-Toxic | Durable and Safe | Upto 20kgs Weight | Orange & White',
        'price' => 1499,
        'category' => 'Fun toys',
        'discount' => 1800,
        'gallery' => 'product_img/p059.webp',
        'description' => '3-in-1 puppy ride-on, rocker and balance board for toddlers.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Jam & Honey Magnetic Fishing Game for Kids  2 Player Toy with 24 Magnetic Fishes, Lights & Music, Rechargeable with Type-C Charging, Trolley Design',
        'price' => 899,
        'category' => 'Fun toys',
        'discount' => 978,
        'gallery' => 'product_img/p060.webp',
        'description' => 'Magnetic fishing game with lights and music for two players.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'BELOXY Fun Table Top Magnetic Board Game | for Kids and Adults | 28 Magnets, Travel Bag and Lanyard (Style 6)',
        'price' => 597,
        'category' => 'Fun toys',
        'discount' => 740,
        'gallery' => 'product_img/p061.webp',
        'description' => 'Tabletop magnetic board game suitable for kids and adults.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Jam & Honey Remote Control Car for Kids | High-Speed RC Car with Rechargeable Lithium Battery | Type-C Charging | LED Headlights | Graffiti Blue',
        'price' => 1209,
        'category' => 'Fun toys',
        'discount' => 1329,
        'gallery' => 'product_img/p062.webp',
        'description' => 'High-speed remote control car with rechargeable battery and LED lights.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Jam & Honey Soft Penguin Plush Toy for Kids | Soft Toy for Boys and Girls | Super-Soft and Safe| Ideal for Gifting | Height 17 cm | Black and White',
        'price' => 300,
        'category' => 'Fun toys',
        'discount' => 670,
        'gallery' => 'product_img/p063.webp',
        'description' => 'Soft and safe penguin plush toy perfect for kids and gifting.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Toyshine 2 in 1 Ring Toss Game | Shape Sorter Color Recognition Aim and Strike Game - Multicolor',
        'price' => 199,
        'category' => 'Fun toys',
        'discount' => 280,
        'gallery' => 'product_img/p064.webp',
        'description' => '2-in-1 ring toss and shape sorter game for color recognition and fun.',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    
         [
            'name' => 'Symbol Men 100% Polyester Regular Jacket',
            'price' => 1499,
            'category' => 'Brands',
            'discount' => 1500,
            'gallery' => 'product_img/p066.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Solimo Antimicrobial Modular Plastic Storage Containers with Lid (2400 ml each) | Stackable | BPA-Free | Microwave Safe | Multipurpose Use for Snacks, Spices, & more (Set of 4) (Black)',
            'price' => 899,
            'category' => 'Brands',
            'discount' => 1186,
            'gallery' => 'product_img/p067.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Solimo Camera Glass Lens Protector Ring for Realme P3X 5G Case Friendly with Edge to Edge Coverage and Easy Installation (Gold)',
            'price' => 199,
            'category' => 'Brands',
            'discount' => 300,
            'gallery' => 'product_img/p068.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Solimo Bicycle Frame Saddle Bag with Touchscreen Pocket for Smartphone',
            'price' => 499,
            'category' => 'Brands',
            'discount' => 800,
            'gallery' => 'product_img/p069.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Umi Designer Vintage Tape Recorder MDF Wooden Key Holder for Home and Office Décor',
            'price' => 199,
            'category' => 'Brands',
            'discount' => 278,
            'gallery' => 'product_img/p070.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Odestar Wooden Hanging Wall Mirror for Living Room Bedroom Dressing Table Mirror Makeup Mirror Perfect for Any Room Home Decor Item Rectangular (Size 12x35x80 Cm) Black-',
            'price' => 2209,
            'category' => 'Brands',
            'discount' => 3740,
            'gallery' => 'product_img/p071.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Tisany Desk Shelf Clamp-On Above or Under - 22 inch Clamp Desktop Shelf, Over or Under Table Clamp Shelf, Desk Organizer Shelf for Office, Black(Tool Free Installation)',
            'price' => 1209,
            'category' => 'Brands',
            'discount' => 1779,
            'gallery' => 'product_img/p072.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'ANY TIME Non Woven Hanging Jewelry Organizer (Pack Of 1) (Pink)',
            'price' => 300,
            'category' => 'Brands',
            'discount' => 670,
            'gallery' => 'product_img/p073.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Solimo 3-Door Foldable Wardrobe, 10 Racks, Brown (Plastic,Fabric)',
            'price' => 199,
            'category' => 'Brands',
            'discount' => 280,
            'gallery' => 'product_img/p074.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Hello Fall Quote On Chop Board Theme Wall Art For Fall Decoration| Fall Season Home Decor Item | Home Decoration Wall Hanging',
            'price' => 199,
            'category' => 'Brands',
            'discount' => 280,
            'gallery' => 'product_img/p075.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Non-Stick Cookware Set with Detachable Handle | Granite Finish | Induction Base | Pfoa Free | HTR Exterior Coating | Black',
            'price' => 1499,
            'category' => 'cook',
            'discount' => 1500,
            'gallery' => 'product_img/p076.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Non-Stick Cookware Set with Detachable Handle| Granite Finish | Induction Base | Pfoa Free | HTR Exterior Coating | Black',
            'price' => 899,
            'category' => 'cook',
            'discount' => 1186,
            'gallery' => 'product_img/p077.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Triply Stainless Steel 3 Piece Cookware Set(Kadhai/Wok 24 Cm, Fry Pan - 24 Cm with Common Lid & Tea/Milk Saucepan-16 Cm) Induction and Gas Stove Compatible, Silver',
            'price' => 199,
            'category' => 'cook',
            'discount' => 300,
            'gallery' => 'product_img/p078.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' Stainless Steel Tope Set with Lid; 1L ; 1.4L; 1.8L; Set of 3 Pieces, Silver',
            'price' => 499,
            'category' => 'cook',
            'discount' => 800,
            'gallery' => 'product_img/p079.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' 12 Pc Ceramic Cookware Set Nonstick, Pots and Pans Set Non Stick for Kitchen with Frying Pan, Sauce Pan, Pots and Pans for Cooking, Non Toxic Cookware Sets, Oven and Dishwasher Safe',
            'price' => 33199,
            'category' => 'cook',
            'discount' => 38278,
            'gallery' => 'product_img/p080.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'XML Bottle Cleaning Brush Silicone Long Handle for Baby Bottle, Water Bottle, Containers, Vase and Glass, Bottle Cleaner for Home and Kitchen Accessories Item Products (28-CM-Silicone-Grey-Brush)',
            'price' => 209,
            'category' => 'cook',
            'discount' => 440,
            'gallery' => 'product_img/p081.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => '12FOR COLLECTION Stainless Steel 2 Tier Countertop Kitchen Rack|Pantry Storage Organizer | Multipurpose Storage Organizer | Kitchen Racks | Kitchen Organizer | Kitchen Accessories Rack, Tiered Shelf',
            'price' => 1209,
            'category' => 'cook',
            'discount' => 1779,
            'gallery' => 'product_img/p082.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'CBK Dish Drying Mat for Kitchen Drying mat for Kitchen Utensils Water Absorbent mat Large Dry mat for Kitchen Utensils Kitchen Linens Place mats for Home (30 Cm * 40 Cm) (Pack of 1)',
            'price' => 300,
            'category' => 'cook',
            'discount' => 670,
            'gallery' => 'product_img/p083.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'HOME SKILL® Knife for Kitchen use Stainless Steel 3 Pieces Professional Kitchen Knife for Meat Chef Knife with Non-Slip Ergonomic Handle Sharp Manual Sharpening for Home Kitchen (Black)',
            'price' => 199,
            'category' => 'cook',
            'discount' => 280,
            'gallery' => 'product_img/p084.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'GOLWYN Premium Self Adhesive Kitchen Accessories Items Organizer Rack Stand, Wall Hanging Hooks Strong Without Drilling/Bathroom Door Cloth Hanger (9 Hooks), Stainless Steel',
            'price' => 220,
            'category' => 'cook',
            'discount' => 280,
            'gallery' => 'product_img/p085.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Start Your Engines: My Unstoppable CrossFit Journey',
            'price' => 499,
            'category' => 'fitness journey',
            'discount' => 800,
            'gallery' => 'product_img/p086.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'The Beginner Body Blueprint: Simple Exercises, Daily Routines, and Motivation to Start Your Fitness Journey Today',
            'price' => 899,
            'category' => 'fitness journey',
            'discount' => 1186,
            'gallery' => 'product_img/p087.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' Introduction to Pre-Apocalyptic Fitness: Start Your Fitness Journey for Lifelong Preparedness',
            'price' => 199,
            'category' => 'fitness journey',
            'discount' => 300,
            'gallery' => 'product_img/p088.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' Quick Guide On How To Start Your Fitness Journey',
            'price' => 499,
            'category' => 'fitness journey',
            'discount' => 800,
            'gallery' => 'product_img/p089.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' How To Kick Start Your Fitness Journey: The No-Nonsense Guide (The No-Nonsense Fitness Guides by A2S Fitness)',
            'price' => 199,
            'category' => 'fitness journey',
            'discount' => 278,
            'gallery' => 'product_img/p090.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Yoga for Beginners: Start Your Journey Today (Smart Reads: Understanding the World)',
            'price' => 209,
            'category' => 'fitness journey',
            'discount' => 440,
            'gallery' => 'product_img/p091.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Simple Fitness Routines to Start Your Exercise Journey: Beginner-Friendly Workouts to Build Strength, Boost Energy, and Create a Healthier Lifestyle',
            'price' => 1209,
            'category' => 'fitness journey',
            'discount' => 1779,
            'gallery' => 'product_img/p092.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Dont Wait To Lose Weight: 10 Steps to Kick-Start Your Fitness Journey',
            'price' => 300,
            'category' => 'fitness journey',
            'discount' => 670,
            'gallery' => 'product_img/p093.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => '7 Highly effective tips on how to start & stick to your fitness journey: Enough Excuses!!',
            'price' => 199,
            'category' => 'fitness journey',
            'discount' => 280,
            'gallery' => 'product_img/p094.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Mindfulness: The Most Effective Techniques: Connect With Your Inner Self To Reach Your Goals Easily and Peacefully (Down-to-Earth Spirituality for Everyday People)',
            'price' => 220,
            'category' => 'fitness journey',
            'discount' => 280,
            'gallery' => 'product_img/p095.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Castiqa Microfibre Unique Patterns 2021 Launches Diwan Set Covers 8 Pcs Set of 1 Bedsheet 2 Bolsters and 5 Cushion Covers (Kids Steal Grey)',
            'price' => 499,
            'category' => 'Furniture',
            'discount' => 800,
            'gallery' => 'product_img/p096.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Castiqa Microfiber Fabric Abstract Design 8 Pcs Diwan Set Covers of 1 Bedsheet 2 Bolster Covers 5 Cushion Covers (Steal Grey (Cats Print))',
            'price' => 899,
            'category' => 'Furniture',
            'discount' => 1186,
            'gallery' => 'product_img/p097.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' Fascination FASINATION 4PC Metal Furniture Legs, Latest Style Coffee Table Sofa Feet Kitchen Table Legs Bathroom Cabinet Cupboard Feet, DIY Furniture Hardware, 6 Inch,Rose Gold',
            'price' => 1699,
            'category' => 'Furniture',
            'discount' => 2000,
            'gallery' => 'product_img/p098.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' Corazzin Rattan Wicker 2 Seater Cushioned Patio Table And Chair Set Garden Coffee Table Set With 1 Table And 2 Chairs Set Outdoor Furniture (Brown) - 28 Inch, 30 Inch',
            'price' => 12499,
            'category' => 'Furniture',
            'discount' => 14800,
            'gallery' => 'product_img/p099.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' CRAFT MANIACS ONE Direction Steal My Girl 16*16 INCHES Pillow with Filler | Merch for ONE D Lovers',
            'price' => 199,
            'category' => 'Furniture',
            'discount' => 278,
            'gallery' => 'product_img/p0100.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Nubilous Tap Extender for Kitchen Sink, Flexible Faucet with Tap Extension for Convenient Use Upgrade Your Kitchen Sink with Flexible Tap for Easy Access',
            'price' => 209,
            'category' => 'Furniture',
            'discount' => 440,
            'gallery' => 'product_img/p0101.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Wazdorf Sealing Clip - Portable Mini Sealing Machine Handheld Packet Sealer for Food, Snacks, Chips, Fresh Storage, Plastic Bag Sealing Machine',
            'price' => 109,
            'category' => 'Furniture',
            'discount' => 179,
            'gallery' => 'product_img/p0102.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'METIER Steal Napkin Holder - Set Of 1 Pc',
            'price' => 300,
            'category' => 'Furniture',
            'discount' => 670,
            'gallery' => 'product_img/p0103.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Estylo Towel Rod24" -Sleek with Stainless Steal Pipe (Chrome Finished)',
            'price' => 199,
            'category' => 'Furniture',
            'discount' => 280,
            'gallery' => 'product_img/p0104.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'DARKZONE Steal Stainless Steel Self Adhesive 4 Arm Bathroom Swing Hanger Towel Rack',
            'price' => 1998,
            'category' => 'Furniture',
            'discount' => 2580,
            'gallery' => 'product_img/p0105.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Samsung Galaxy M05 (Mint Green, 4GB RAM, 64 GB Storage) | 50MP Dual Camera | Bigger 6.7" HD+ Display | 5000mAh Battery | 25W Fast Charging | 2 Gen OS Upgrade & 4 Year Security Update | Without Charger',
            'price' => 6499,
            'category' => 'mobile',
            'discount' => 9999,
            'gallery' => 'product_img/p0106.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Apple 20W USB-C Power Adapter (for iPhone, iPad & AirPods)',
            'price' => 1399,
            'category' => 'mobile',
            'discount' => 1686,
            'gallery' => 'product_img/p0107.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' Ambrane 2 in 1 OTG Adapter Micro USB+USB Type C to USB Female Connector, OTG Pen Drive Adapter to Mobile Connector Type C, Compatible with All Devices',
            'price' => 199,
            'category' => 'mobile',
            'discount' => 270,
            'gallery' => 'product_img/p0108.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' Samsung Galaxy S24 Ultra 5G AI Smartphone with Galaxy AI (Titanium Black, 12GB, 256GB Storage), Snapdragon 8 Gen 3, 200 MP Camera with ProVisual Engine and 5000mAh Battery',
            'price' => 84999,
            'category' => 'mobile',
            'discount' => 134999,
            'gallery' => 'product_img/p0109.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' Redmi A4 5G (Sparkle Purple, 4GB RAM, 128GB Storage) | Global Debut SD 4s Gen 2 | Segment Largest 6.88in 120Hz | 50MP Dual Camera | 18W Fast Charging',
            'price' => 9499,
            'category' => 'mobile',
            'discount' => 13999,
            'gallery' => 'product_img/p0110.jpg',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'OnePlus Nord CE4 Lite 5G (Super Silver, 8GB RAM, 128GB Storage) | Lifetime Display Warranty | 5500 mAh Battery, 80W SUPERVOOC and Reverse Charging | 50MP Camera with OIS | 120Hz AMOLED Display',
            'price' => 17999,
            'category' => 'mobile',
            'discount' => 20999,
            'gallery' => 'product_img/p0111.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Portronics iKonnect C Pro Type C to 3.5 mm Audio Jack Connector with DAC Headphone Converter Adapter Compatible with iPhone 15 Pro Max/15 Pro/15 Plus, Galaxy S23/S22/S21/S208 & Other Type C Phones',
            'price' => 109,
            'category' => 'mobile',
            'discount' => 179,
            'gallery' => 'product_img/p0112.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Apple iPhone 15 (128 GB) - Black',
            'price' => 59700,
            'category' => 'mobile',
            'discount' => 65900,
            'gallery' => 'product_img/p0113.webp',
            'description' => 'Creative LEGO building block set for all ages',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'iQOO Z9 Lite 5G (Aqua Flow, 6GB RAM, 128GB Storage) | Dimensity 6300 5G | 50MP Sony AI Camera | Charger in The Box',
            'price' => 11999,
            'category' => 'mobile',
            'discount' => 15999,
            'gallery' => 'product_img/p0114.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Portronics Konnect L POR-1403 Fast Charging 3A Type-C Cable 1.2 Meter with Charge & Sync Function for All Type-C Devices (White)',
            'price' => 119,
            'category' => 'mobile',
            'discount' => 199,
            'gallery' => 'product_img/p0115.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Ambrane Magsafe Wireless 10000Mah Fast Charging USB Type-C Input Power Bank, Strong Magnet, 22.5W Output For iPhone 12 & Above, Android & Other Qi Enabled Devices + Magnetic Ring (Aerosync Snap, Blue)',
            'price' => 1199,
            'category' => 'mobile',
            'discount' => 1499,
            'gallery' => 'product_img/p0116.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'SAMSUNG EVO Plus 128GB Micro SDXC w/SD Adaptor, Up-to 160MB/s, Expanded Storage for Gaming Devices, Android Tablets and Smart Phones, Memory Card, MB-MC128SA/IN ',
            'price' => 1199,
            'category' => 'mobile',
            'discount' => 1499,
            'gallery' => 'product_img/p0117.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Portronics Konnect B Micro USB Cables For Fast Charging & Data Sync 3.0 Amp with PVC Heads I Nylon Braided I 1 mtr(Black)',
            'price' => 99,
            'category' => 'mobile',
            'discount' => 370,
            'gallery' => 'product_img/p0118.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'pTron Dynamo Power 20000mAh 22.5W Super Fast Charging, USB Type-C Input Power Bank with Quick Charge & 20W Power Delivery, Built-in Charging Cables, 4 Outputs, Type-C Input/Output Port (Black)',
            'price' => 1299,
            'category' => 'mobile',
            'discount' => 1499,
            'gallery' => 'product_img/p0119.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'iQOO Z9s 5G (Titanium Matte, 8GB RAM, 256GB Storage) | 120 Hz 3D Curved AMOLED Display | 5500 mAh Ultra-Thin Battery | Dimesity 7300 5G Processor | Sony IMX882 OIS Camera with Aura Light',
            'price' => 20999,
            'category' => 'mobile',
            'discount' => 28999,
            'gallery' => 'product_img/p0120.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'NoiseFit Halo 1.43" AMOLED Display, Bluetooth Calling Round Dial Smart Watch, Premium Metallic Build, Always on Display, Smart Gesture Control, 100 Sports Modes (Vintage Brown)',
            'price' => 2499,
            'category' => 'Electronics',
            'discount' => 4999,
            'gallery' => 'product_img/p0121.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Noise Newly Launched Halo 2 Smart Watch 1st Ever Functional Rotating Dial (Axe-Cut Bezel), 1.43" AMOLED, Stainless Steel Build, Custom Transition Effects, BT Calling, Health Suite (Vintage Brown)',
            'price' => 4399,
            'category' => 'Electronics',
            'discount' => 8686,
            'gallery' => 'product_img/p0122.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' Noise ColorFit Ultra 3 Bluetooth Calling Smart Watch with Biggest 1.96" AMOLED Display, Premium Metallic Build, Functional Crown, Gesture Control with Metallic Strap (Jet Black: Elite Edition)',
            'price' => 2999,
            'category' => 'Electronics',
            'discount' => 4999,
            'gallery' => 'product_img/p0123.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' Fastrack Astor FR2 Pro Smart Watch, 1.43” AMOLED Display, 466 * 466 Pixel Resolution, SingleSync BT Calling, AI Voice Assistant, 100+ Sports Modes and Smartwatch Faces, IP68 (Black)',
            'price' => 2999,
            'category' => 'Electronics',
            'discount' => 5999,
            'gallery' => 'product_img/p0124.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => ' MARVIK Smart Watch for Kids, Men, Boys, Girls, and Women, D20 Plus 2025, Latest for Android and iOS Phones, IP68 Waterproof with Daily Activity Tracker, Heart Rate Sensor, Sleep Monitor Watch - Black',
            'price' => 499,
            'category' => 'Electronics',
            'discount' => 999,
            'gallery' => 'product_img/p0125.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Watches for Men Fashion Diamond Analog Quartz Men Easy Reader Watch Stainsteel Steel Date Waterproof Luminous Business Watch',
            'price' => 3999,
            'category' => 'Electronics',
            'discount' => 8999,
            'gallery' => 'product_img/p0126.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Skmei New Car Wheel Watch with Rolling Creative Fashion Analog Watch, Black Dial Zink Alloy Case Mens Watch, Stainless Steel Black Color Band, Quartz Movement, Water & Scratch-Resistant-1990',
            'price' => 1709,
            'category' => 'Electronics',
            'discount' => 2979,
            'gallery' => 'product_img/p0127.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'boAt Airdopes 121 Pro Plus, 100HRS Battery, 4Mics ENx, 50ms Low Latency, Fast Charge, LED Display, IPX5, v5.3 Bluetooth in Ear Earbuds, TWS Ear Buds Wireless Earphones with mic (Black)',
            'price' => 1700,
            'category' => 'Electronics',
            'discount' => 2900,
            'gallery' => 'product_img/p0128.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'boAt Airdopes 111v2, Premium Leather Finish, 4Mics ENx, 50HRS Battery, 13mm Drivers, Fast Charge, Dual Pair, v5.4 Bluetooth TWS in Ear Earbuds Wireless Earphones with mic (Classic Black)',
            'price' => 1999,
            'category' => 'Electronics',
            'discount' => 2999,
            'gallery' => 'product_img/p0129.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'boAt Airdopes 311 Pro, 50HRS Battery, Fast Charge, Dual Mics ENx Tech, Transparent LID, Low Latency, IPX4, IWP Tech, v5.3 Bluetooth Earbuds, TWS Ear Buds Wireless Earphones with mic (Active Black)',
            'price' => 999,
            'category' => 'Electronics',
            'discount' => 1999,
            'gallery' => 'product_img/p0130.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Boult Z60 Truly Wireless in Ear Earbuds with 60H Playtime, Zen™ ENC Mic, 50ms Low Latency, 13mm Bass Drivers, Type-C Fast Charging, Made in India, BT V5.3, Touch Control, IPX5 Ear Buds (Powder Blue)',
            'price' => 700,
            'category' => 'Electronics',
            'discount' => 900,
            'gallery' => 'product_img/p0131.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Apple AirPods 4 Wireless Earbuds, Bluetooth Headphones, Personalised Spatial Audio, Sweat and Water Resistant, USB-C Charging Case, H2 Chip, Up to 30 Hours of Battery Life, Effortless Setup for iPhone',
            'price' => 11999,
            'category' => 'Electronics',
            'discount' => 15999,
            'gallery' => 'product_img/p0132.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'iPhonee Headphones(2 Generation)Wireless Earbuds,Bluetooth,H2 Chip,Spatial Audio,Sweat & Water Resistant,USB-C Charging Case,65 Hours of Battery Life,Easy Setup for iPhone,Apple Compatible (2Gen_USA)',
            'price' => 3119,
            'category' => 'Electronics',
            'discount' => 4199,
            'gallery' => 'product_img/p0133.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Boult Mustang Newly Launched Torq TWS Earbuds with 60H Playtime, App Support, 4 Mics, ENC, 45ms Low Latency, 13mm Driver, Breathing LEDs,Touch Control, Made in India, IPX5, Ear Buds Wireless (Yellow)',
            'price' => 1999,
            'category' => 'Electronics',
            'discount' => 2999,
            'gallery' => 'product_img/p0134.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
         [
            'name' => 'Apple EarPods (USB-C)',
            'price' => 1499,
            'category' => 'Electronics',
            'discount' => 1999,
            'gallery' => 'product_img/p0135.webp',
            'description' => 'Creative LEGO building block set for all ages.',
            'created_at' => now(),
               'updated_at' => now(),
         ],
        
            ]);
            
         }
         }

   
         